axis off
set(gca, ...
    'CameraPosition' , [9 -1 2], ...
	'CameraPositionMode' , 'manual', ...
	'CameraTarget' , [-2 0 0], ...
	'CameraTargetMode' , 'manual', ....
	'CameraViewAngle' , [20], ...
	'CameraViewAngleMode' , 'manual', ...
    'DataAspectRatio', [1 1 1], ...
	'PlotBoxAspectRatioMode' , 'manual', ...
    'OuterPosition', [0 0 1 1], ...
    'Position', [0.13 0.11 0.775 0.815])



tstr = ['t = ',num2str(t-4,'%0.2f')];
text(1,-3,.5,tstr,'fontsize',42);


